version: 2

sphinx:
  configuration: doc/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      # reno requires full repo
      - git fetch --unshallow || true
      - git fetch --all --tags || true
